apiVersion: v1
kind: ServiceAccount
metadata:
  name: ace-burst-test-service-account
  namespace: ace-demo
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ace-demo
  name: ready-change-role
rules:
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ready-change-role-binding
  namespace: ace-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ready-change-role
subjects:
- kind: ServiceAccount
  name: ace-burst-test-service-account
  namespace: ace-demo
